/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router. It is kept in sync here so the GitHub source is immediately runnable.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as AdminLoginRouteImport } from "./routes/admin/login";
import { Route as IndexRouteImport } from "./routes/index";

const AdminRoute = AdminRouteImport.update({ id: "/admin", path: "/admin", getParentRoute: () => rootRouteImport } as any);
const AdminLoginRoute = AdminLoginRouteImport.update({ id: "/login", path: "/login", getParentRoute: () => AdminRoute } as any);
const IndexRoute = IndexRouteImport.update({ id: "/", path: "/", getParentRoute: () => rootRouteImport } as any);

const adminRouteChildren = { AdminLoginRoute };
const rootRouteChildren = { AdminRoute: AdminRoute._addFileChildren(adminRouteChildren), IndexRoute };

export interface FileRoutesByFullPath { "/": typeof IndexRoute; "/admin": typeof AdminRoute; "/admin/login": typeof AdminLoginRoute; }
export interface FileRoutesByTo { "/": typeof IndexRoute; "/admin": typeof AdminRoute; "/admin/login": typeof AdminLoginRoute; }
export interface FileRoutesById { __root__: typeof rootRouteImport; "/": typeof IndexRoute; "/admin": typeof AdminRoute; "/admin/login": typeof AdminLoginRoute; }
export interface FileRouteTypes { fileRoutesByFullPath: FileRoutesByFullPath; fullPaths: "/" | "/admin" | "/admin/login"; fileRoutesByTo: FileRoutesByTo; to: "/" | "/admin" | "/admin/login"; id: "__root__" | "/" | "/admin" | "/admin/login"; fileRoutesById: FileRoutesById; }

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": { id: "/"; path: "/"; fullPath: "/"; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport };
    "/admin": { id: "/admin"; path: "/admin"; fullPath: "/admin"; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport };
    "/admin/login": { id: "/login"; path: "/login"; fullPath: "/admin/login"; preLoaderRoute: typeof AdminLoginRouteImport; parentRoute: typeof AdminRoute };
  }
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" { interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>>; config: Awaited<ReturnType<typeof startInstance.getOptions>>; } }
